/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.tsonglew.jetcdskywalkingdemo;

import com.github.tsonglew.jetcdskywalkingdemo.client.EtcdClient;
import io.etcd.jetcd.ByteSequence;

import java.lang.management.OperatingSystemMXBean;
import java.util.Arrays;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
        throws ExecutionException, InterruptedException, TimeoutException {
        System.out.println(new App().getGreeting());
        var etcdClient = new EtcdClient();
        etcdClient.getKvClient().put(ByteSequence.from("test".getBytes()), ByteSequence.from("test".getBytes())).get();
        System.out.println("put finished");
        var result = etcdClient.getKvClient().get(ByteSequence.from("test".getBytes())).get(3, TimeUnit.SECONDS);
        System.out.println("result: " + Arrays.toString(result.getKvs().toArray()));
        etcdClient.getKvClient().close();
        System.exit(0);

    }
}
